---
title: "HDT2"
output: html_document
date: '2022-08-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("shiny")
install.packages("plotly")
```

```{r}
#install.packages("forecast")
##install.packages("fUnitRoots")
#install.packages("ggfortify")

library(forecast)
library(tseries)
library(fUnitRoots)
library(ggfortify)
library(readxl)
library(ggplot2)
library(shiny)
library(lubridate)
library(plotly)
getwd()
```


```{r}
df_consumo <- read_excel("CONSUMO-2022-05.xlsx", range="B7:G276")
df_importacion <- read_excel("IMPORTACION-VOLUMEN-2022-05.xlsx", range="B7:G264")

df_consumo$Diesel <- df_consumo$`Diesel alto azufre`+df_consumo$`Diesel bajo azufre`
df_consumo$`Diesel alto azufre` <- NULL
df_consumo$`Diesel bajo azufre` <- NULL
df_consumo[4] <- NULL
#head(df_consumo)

#

#summary(df_consumo)
#plot(df_consumo$Fecha, df_consumo$`Gasolina superior`, xlab="FECHA", ylab="CONSUMO GASOLINA SUPERIOR", col= "blue")
#points(df_consumo$Fecha, df_consumo$Diesel, col = "green", pch = 19)
#points(df_consumo$Fecha, df_consumo$`Gasolina regular`, col = "red", pch = 19)

#
#height<- dnorm(df_consumo$`Gasolina superior`, mean(df_consumo$`Gasolina superior`), sd(df_consumo$`Gasolina #superior`))
#plot(df_consumo$`Gasolina superior`, height)
df_importacion$Diesel <- df_importacion$`Diesel alto azufre`+df_importacion$`Diesel bajo azufre`
df_importacion$`Diesel alto azufre` <- NULL
df_importacion$`Diesel bajo azufre` <- NULL
df_importacion[4] <- NULL


Consumo_Diesel <- ts(df_consumo$Diesel, start=c(2000, 1), frequency = 12)
Consumo_regular <- ts(df_consumo$`Gasolina regular`, start=c(2000, 1), frequency = 12)
Consumo_super <- ts(df_consumo$`Gasolina superior`, start=c(2000, 1), frequency = 12)
importacion_Diesel <- ts(df_importacion$Diesel, start=c(2000, 1), frequency = 12)
importacion_regular <- ts(df_importacion$`Gasolina regular`, start=c(2000, 1), frequency = 12)
importacion_super <- ts(df_importacion$`Gasolina superior`, start=c(2000, 1), frequency = 12)



```

```{r}
ConsDieselModel<-read.csv("consumo_diesel_model.csv")
ConsDieselModel<-ts(ConsDieselModel$Data, start=c(2000, 1), frequency = 12)

ImpDieselModel<-read.csv("importacion_diesel_model.csv")
ImpDieselModel<-ts(ImpDieselModel$Data, start=c(2000, 1), frequency = 12)

ConsRegModel<-read.csv("consumo_regular_model.csv")
ConsRegModel<-ts(ConsRegModel$Data, start=c(2000, 1), frequency = 12)

ImpRegModel<-read.csv("importacion_regular_model.csv")
ImpRegModel<-ts(ImpRegModel$Data, start=c(2000, 1), frequency = 12)

ConsSuperModel<-read.csv("consumo_super_model.csv")
ConsSuperModel<-ts(ConsSuperModel$Data, start=c(2000, 1), frequency = 12)

ImpSuperModel<-read.csv("importacion_super_model.csv")
ImpSuperModel<-ts(ImpSuperModel$Data, start=c(2000, 1), frequency = 12)
```


```{r}

dec_cons_Diesel <- decompose(ConsDieselModel)
dec_cons_Diesel$Date = time(ConsDieselModel)
dec_imp_Diesel <- decompose(ImpDieselModel)
dec_imp_Diesel$Date = time(ImpDieselModel)

dec_cons_super <- decompose(ConsSuperModel)
dec_cons_super$Date <- time(ConsSuperModel)
dec_imp_super <- decompose(ImpSuperModel)
dec_imp_super$Date <- time(ImpSuperModel)

dec_cons_regular <- decompose(ConsRegModel)
dec_cons_regular$Date <- time(ConsRegModel)
dec_imp_regular <- decompose(ImpRegModel)
dec_imp_regular$Date <- time(ImpRegModel)

```

```{r}
pallette = c(rgb(71/255, 169/255, 247/255), rgb(111/255, 59/255, 128/255), rgb(76/255, 16/255, 54/255))
```


```{r}
ui <- fluidPage(

  # App title ----
  titlePanel("CONSUMO DE COMBUSTIBLES"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    
    # Sidebar panel for inputs ----
    sidebarPanel(
        helpText("Seleccione la información que desea visualizar:"),

      checkboxGroupInput(
        inputId="typesOfFuel",
        label="Tipos de combustible",
        list("SUPER","REGULAR","DIESEL"),
        selected = "DIESEL"
        ),
      selectInput(
        inputId="typeOfMetric",
        label="Datos de:",
        list("CONSUMO","IMPORTACION"),
        selected = "CONSUMO",
        multiple = FALSE,
        selectize = TRUE,
        width = NULL,
        size = NULL
        ),
        checkboxGroupInput(
        inputId="DataSlicesShown",
        label="Mostrar:",
        choices = list("TENDENCIA", "ESTACIONALIDAD", "RUIDO"),
        selected = "TENDENCIA"
        ),
      dateRangeInput(
        inputId = "DDR",
        label = "Mostrar desde:",
        start = "2000-1-1",
        end = "2025-5-1",
        min = "2000-1-1",
        max = "2025-5-1",
        format = "dd-M-yyyy",
        startview = "month",
        weekstart = 0,
        language = "es",
        separator = " a ",
        width = NULL,
        autoclose = TRUE
        ),
      dateInput(
        inputId = "BarsMonth",
        label = "Mes para diagrama de barras:",
        value = "2000-5-1",
        min = "2000-5-1",
        max = "2025-5-1",
        format = "M-yyyy",
        startview = "month",
        weekstart = 0,
        language = "es"
      )
      
      
      
      ),
    


    mainPanel(
      verticalLayout(
      plotlyOutput(outputId = "MainPlot"),
      plotlyOutput(outputId = "BarPlot")
      )

    )
  )
)

server <- function(input, output) {

    

  output$MainPlot <- renderPlotly({
    min <- c(year(input$DDR[1]), month(input$DDR[1]))
    max <- c(year(input$DDR[2]), month(input$DDR[2]))

    
    IsConsumo <- "CONSUMO" == input$typeOfMetric
    
    Want_Diesel  <- "DIESEL" %in% input$typesOfFuel 
    Want_Regular <- "REGULAR" %in% input$typesOfFuel
    Want_Super   <- "SUPER" %in% input$typesOfFuel
    
    Diesel_desc <- if (IsConsumo) dec_cons_Diesel else dec_imp_Diesel
    Regular_desc <- if (IsConsumo) dec_cons_regular else dec_imp_regular
    Super_desc <- if (IsConsumo) dec_cons_super else dec_imp_super
    
    Weight_Tendency <- if ("TENDENCIA" %in% input$DataSlicesShown) 42 else 0
    Weight_Seasonal <- if ("ESTACIONALIDAD" %in% input$DataSlicesShown) 42 else 0
    Weight_Noise <- if ("RUIDO" %in% input$DataSlicesShown) 42 else 0


    Date <-  window(Diesel_desc$Date, min, max)
    D_trend <- window(Diesel_desc$trend, min, max) * (Weight_Tendency)
    D_seasonal <- window(Diesel_desc$seasonal, min, max) * (Weight_Seasonal)
    D_random <-   window(Diesel_desc$random, min, max) * (Weight_Noise)
    
    R_trend <-    window(Regular_desc$trend, min, max) * (Weight_Tendency)
    R_seasonal <- window(Regular_desc$seasonal, min, max) * (Weight_Seasonal)
    R_random <-   window(Regular_desc$random, min, max) * (Weight_Noise)
    
    S_trend <-    window(Super_desc$trend, min, max) * (Weight_Tendency)
    S_seasonal <- window(Super_desc$seasonal, min, max) * (Weight_Seasonal)
    S_random <-   window(Super_desc$random, min, max) * (Weight_Noise)
    
    total_diesel <- D_trend + D_seasonal + D_random
    total_regular <- R_trend + R_seasonal + R_random
    total_super <- S_trend + S_seasonal + S_random
    plotData <- data.frame(Date, total_diesel, total_regular, total_super)
    
    
    fig <- plot_ly(data= plotData, x=~Date)
    
    if (Want_Diesel){
    fig <- fig %>% add_trace(y=~total_diesel, 
                   line = list(color = pallette[1], width = 1.5), name= "Diesel", type = 'scatter', mode = 'lines')
    }
    if (Want_Regular){
    fig <- fig %>% add_trace(y = ~total_regular, line = list(color = pallette[2], width = 1.5), 
                             name= "Gasolina regular", type = 'scatter', mode = 'lines')
    }
    if (Want_Super){
    fig <- fig %>% add_trace(y = ~total_super, line = list(color = pallette[3], width = 1.5), 
                             name= "Gasolina superior", type = 'scatter', mode = 'lines')
    }
    
    fig <- fig %>% layout(title = if (IsConsumo) "Consumo de combustibles" else "Importación de combustibles",
         xaxis = list(title = "Fecha"),
         yaxis = list (title = "Galones"))
    
    
    fig
  })
  output$BarPlot <- renderPlotly({
        monthFactor <- c(year(input$BarsMonth), month(input$BarsMonth))
        print(monthFactor)
        
       
    
        
        Cons_Diesel_desc <- dec_cons_Diesel 
        Cons_Diesel_desc <- window(Cons_Diesel_desc$x, monthFactor, monthFactor)
        Cons_Regular_desc <- dec_cons_regular
        Cons_Regular_desc <- window(Cons_Regular_desc$x, monthFactor, monthFactor)
        Cons_Super_desc <- dec_cons_super 
        Cons_Super_desc <- window(Cons_Super_desc$x, monthFactor, monthFactor)
        
        
        Imp_Diesel_desc <- dec_imp_Diesel 
        Imp_Diesel_desc <- window(Imp_Diesel_desc$x, monthFactor, monthFactor)
        Imp_Regular_desc <- dec_imp_regular
        Imp_Regular_desc <- window(Imp_Regular_desc$x, monthFactor, monthFactor)
        Imp_Super_desc <- dec_imp_super 
        Imp_Super_desc <- window(Imp_Super_desc$x, monthFactor, monthFactor)
        
        
        fig <- plot_ly(
          x = c("Diesel", "Regular", "Super"),
          y = c(Cons_Diesel_desc, Cons_Regular_desc, Cons_Super_desc),
          name = "Consumo de combustibles",
          type = "bar",
          marker = list(color = pallette[2],
                      line = list(color = 'rgb(0,0,0)',
                                  width = 1.5)))
        fig <- fig %>% add_trace(y = c(Imp_Diesel_desc, Imp_Regular_desc, Imp_Super_desc), name = "Importación de combustibles",
          marker = list(color = pallette[1],
                      line = list(color = 'rgb(0,0,0)',
                                  width = 1.5)))
        fig <- fig %>% layout(yaxis = list(title = 'Barriles'), barmode = 'stack')
        fig
  })
  


}

shinyApp(ui = ui, server = server)
runApp("my_app")

```
```{r}
window(dec_cons_Diesel$x, start=c(2010, 3), end=c(2010, 3))
```



```{r}

Consumo_Diesel <- ts(df_consumo$Diesel, start=c(2000, 1), frequency = 12)
Consumo_regular <- ts(df_consumo$`Gasolina regular`, start=c(2000, 1), frequency = 12)
Consumo_super <- ts(df_consumo$`Gasolina superior`, start=c(2000, 1), frequency = 12)
importacion_Diesel <- ts(df_importacion$Diesel, start=c(2000, 1), frequency = 12)
importacion_regular <- ts(df_importacion$`Gasolina regular`, start=c(2000, 1), frequency = 12)
importacion_super <- ts(df_importacion$`Gasolina superior`, start=c(2000, 1), frequency = 12)


plot(Consumo_Diesel)
plot(Consumo_regular)
plot(Consumo_super)
plot(importacion_Diesel)
plot(importacion_regular)
plot(importacion_super)

```
```{r}
getwd()
dec_cons_super <- decompose(Consumo_super)
plot(dec_cons_super$trend)
cons_trend <- dec_cons_super$trend
write.csv(cons_trend,"/export.csv", row.names = FALSE)



getwd()
dec_cons_super <- decompose(Consumo_super)
plot(dec_cons_super$trend)
cons_trend <- dec_cons_super$trend
write.csv(cons_trend,"/export.csv", row.names = FALSE)


```


```{r}
dec_cons_Diesel <- decompose(Consumo_Diesel)
dec_cons_Diesel$Date = time(Consumo_Diesel)
plot(dec_cons_Diesel$Date, dec_cons_Diesel$trend + dec_cons_Diesel$seasonal + dec_cons_Diesel$random,  main="BRUH", 
     ylab = "Barriles", xlab="Fecha", type="l")
```


```{r}
dec_cons_regular <- decompose(Consumo_regular)
plot(dec_cons_regular)
```
```{r}
dec_imp_super <- decompose(importacion_super)
plot(dec_imp_super)
```
```{r}
dec_imp_diesel <- decompose(importacion_Diesel)
plot(dec_imp_diesel)
```
```{r}
dec_imp_regular <- decompose(importacion_regular)
plot(dec_imp_regular)
```
```{r}
plot(Consumo_Diesel)
trans_cons_diesel<-diff(BoxCox(Consumo_Diesel, 20.5))
plot(trans_cons_diesel)
acf(trans_cons_diesel)
adfTest(trans_cons_diesel)
```
```{r}
plot(Consumo_super)
trans_cons_super<-diff(BoxCox(Consumo_super, 15))
plot(trans_cons_super)
acf(trans_cons_super)
adfTest(trans_cons_super)
```
```{r}
plot(Consumo_regular)
trans_cons_regular<-diff(BoxCox(Consumo_regular, 18))
plot(trans_cons_regular)
acf(trans_cons_regular)
adfTest(trans_cons_regular)
```
```{r}
plot(importacion_Diesel)
trans_imp_diesel<-diff(BoxCox(importacion_Diesel, 15.5))
plot(trans_imp_diesel)
acf(trans_imp_diesel)
adfTest(trans_imp_diesel)
```
```{r}
plot(importacion_super)
trans_imp_super<-diff(BoxCox(importacion_super, 8.6))
plot(trans_imp_super)
acf(trans_imp_super)
adfTest(trans_imp_super)
```
```{r}
plot(importacion_regular)
trans_imp_regular<-diff(BoxCox(importacion_regular, 26.0634467))
plot(trans_imp_regular)
acf(trans_imp_regular)
adfTest(trans_imp_regular)

```


```{r}


adfTest(Consumo_super)
adfTest(diff(Consumo_super))


adfTest(Consumo_regular)
adfTest(diff(Consumo_regular))

adfTest(Consumo_Diesel)
adfTest(diff(Consumo_Diesel))



adfTest(importacion_Diesel)
adfTest(diff(importacion_Diesel))


adfTest(importacion_regular)
adfTest(diff(importacion_regular))

adfTest(importacion_super)
adfTest(diff(importacion_super))

## MODELOS DIESEL
auto.arima(Consumo_Diesel)

fit_consumo_diesel <- arima(log(Consumo_Diesel), c(3, 0, 1),seasonal = list(order = c(1, 1, 2), period = 12))
forecastAP_Consumo_Diesel <- forecast(fit_consumo_diesel, level = c(95), h = 3*12)
autoplot(forecastAP_Consumo_Diesel)



pred <- predict(fit_consumo_diesel, n.ahead = 3*12)
ts.plot(Consumo_Diesel,2.756^pred$pred, log = "y", lty = c(1,3))
## une la tS real y la prediccion 

merged_ts <- ts(c(Consumo_Diesel, 2.756^pred$pred),               
   start = start(Consumo_Diesel),
   frequency = frequency(Consumo_Diesel))
merged_ts

ts.plot(merged_ts)

converted <- fortify(
  merged_ts,
  data = NULL,
  columns = NULL,
  is.date = NULL,
  index.name = "Index",
  data.name = "Data",
  scale = FALSE,
  melt = FALSE
)
write.csv(converted,"consumo_diesel_model.csv", row.names = FALSE)



auto.arima(importacion_Diesel)

fit_importacion_diesel <- arima(log(importacion_Diesel), c(3, 1, 1),seasonal = list(order = c(1, 1, 2), period = 12))
forecastAP_Importacion_Diesel <- forecast(fit_importacion_diesel, level = c(95), h = 3*12)
autoplot(forecastAP_Importacion_Diesel)

## importacion de diesel
pred <- predict(fit_importacion_diesel, n.ahead = 3*12)
ts.plot(importacion_Diesel,2.756^pred$pred, log = "y", lty = c(1,3))

merged_ts <- ts(c(importacion_Diesel, 2.756^pred$pred),               
   start = start(importacion_Diesel),
   frequency = frequency(importacion_Diesel))
merged_ts

ts.plot(merged_ts)

converted <- fortify(
  merged_ts,
  data = NULL,
  columns = NULL,
  is.date = NULL,
  index.name = "Index",
  data.name = "Data",
  scale = FALSE,
  melt = FALSE
)
write.csv(converted,"importacion_diesel_model.csv", row.names = FALSE)






## REGULAR

auto.arima(importacion_regular)

fit_importacion_regular <- arima(log(importacion_regular), c(1, 1, 2),seasonal = list(order = c(1, 1, 2), period = 12))
forecastAP_Importacion_Regular <- forecast(fit_importacion_regular, level = c(95), h = 3*12)
autoplot(forecastAP_Importacion_Regular)

pred <- predict(fit_importacion_regular, n.ahead = 3*12)
ts.plot(importacion_regular,2.756^pred$pred, log = "y", lty = c(1,3))

merged_ts <- ts(c(importacion_regular, 2.756^pred$pred),               
   start = start(importacion_regular),
   frequency = frequency(importacion_regular))
merged_ts

ts.plot(merged_ts)

converted <- fortify(
  merged_ts,
  data = NULL,
  columns = NULL,
  is.date = NULL,
  index.name = "Index",
  data.name = "Data",
  scale = FALSE,
  melt = FALSE
)
write.csv(converted,"importacion_regular_model.csv", row.names = FALSE)









auto.arima(Consumo_regular)

fit_consumo_regular <- arima(log(Consumo_regular), c(1, 1, 1),seasonal = list(order = c(2, 0, 0), period = 12))
forecastAP_Consumo_Regular <- forecast(fit_consumo_regular, level = c(95), h = 3*12)
autoplot(forecastAP_Consumo_Regular)

pred <- predict(fit_consumo_regular, n.ahead = 3*12)
ts.plot(Consumo_regular,2.756^pred$pred, log = "y", lty = c(1,3))

merged_ts <- ts(c(Consumo_regular, 2.756^pred$pred),               
   start = start(Consumo_regular),
   frequency = frequency(Consumo_regular))
merged_ts

ts.plot(merged_ts)

converted <- fortify(
  merged_ts,
  data = NULL,
  columns = NULL,
  is.date = NULL,
  index.name = "Index",
  data.name = "Data",
  scale = FALSE,
  melt = FALSE
)
write.csv(converted,"consumo_regular_model.csv", row.names = FALSE)

## super
auto.arima(Consumo_super)

fit_consumo_super <- arima(log(Consumo_super), c(1, 1, 1),seasonal = list(order = c(2, 0, 0), period = 12))
forecastAP_Consumo_Super <- forecast(fit_consumo_super, level = c(95), h = 3*12)
autoplot(forecastAP_Consumo_Super)



pred <- predict(fit_consumo_super, n.ahead = 3*12)
ts.plot(Consumo_super,2.756^pred$pred, log = "y", lty = c(1,3))

merged_ts <- ts(c(Consumo_super, 2.756^pred$pred),               
   start = start(Consumo_super),
   frequency = frequency(Consumo_super))
merged_ts

ts.plot(merged_ts)

converted <- fortify(
  merged_ts,
  data = NULL,
  columns = NULL,
  is.date = NULL,
  index.name = "Index",
  data.name = "Data",
  scale = FALSE,
  melt = FALSE
)
write.csv(converted,"consumo_super_model.csv", row.names = FALSE)


auto.arima(importacion_super)

fit_importacion_super <- arima(log(importacion_super), c(2, 1, 1),seasonal = list(order = c(2, 0, 0), period = 12))
forecastAP_importacion_Super <- forecast(fit_importacion_super, level = c(95), h = 3*12)
autoplot(forecastAP_importacion_Super)



pred <- predict(fit_importacion_super, n.ahead = 3*12)
ts.plot(importacion_super,2.756^pred$pred, log = "y", lty = c(1,3))

merged_ts <- ts(c(importacion_super, 2.756^pred$pred),               
   start = start(importacion_super),
   frequency = frequency(importacion_super))
merged_ts

ts.plot(merged_ts)

converted <- fortify(
  merged_ts,
  data = NULL,
  columns = NULL,
  is.date = NULL,
  index.name = "Index",
  data.name = "Data",
  scale = FALSE,
  melt = FALSE
)
write.csv(converted,"importacion_super_model.csv", row.names = FALSE)


```


